version: '3.7'
services:
  api:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./content:/content
    env_file:
      - .env
    environment:
      - API_HOST=https://frienda-api.semolik.ru
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure
  db:
    env_file:
      - .env
    image: postgres:16
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 1s
      timeout: 5s
      retries: 30
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: always
  rabbitmq:
    restart: always
    image: "rabbitmq:3"
    env_file:
      - .env
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
  mailserver:
    image: analogic/poste.io
    container_name: mailserver
    restart: unless-stopped
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
      - "8080:8080"
    environment:
      - VIRTUAL_HOST=frienda.semolik.ru
      - HTTPS=OFF
      - HTTP_PORT=8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /nginx/htmlnginx/html/.well-known:/opt/www/.well-known
      - ./mailserver:/data
