version: '3.7'
services:
  api:
    build: ./app
    ports:
      - "8016:8000"
    volumes:
      - ./app:/app
      - ./content:/content
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  db:
    env_file:
      - .env
    image: postgres:16
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 1s
      timeout: 5s
      retries: 30

  rabbitmq:
    image: "rabbitmq:3"
    env_file:
      - .env
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  smtp4dev:
    image: rnwood/smtp4dev:v3
    ports:
      - 1080:80
    volumes:
      - /smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=$EMAIL_SERVER
      - RelayOptions__Login=$EMAIL_USERNAME
      - RelayOptions__Password=$EMAIL_PASSWORD
