version: '3.7'
services:
  api:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./content:/content
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  db:
    env_file:
      - .env
    image: postgres:16
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 1s
      timeout: 5s
      retries: 30
    volumes:
      - ./db-data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3"
    env_file:
      - .env
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
