"""delete messages cascade

Revision ID: 267eeaf93966
Revises: 
Create Date: 2024-03-05 13:52:21.503433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '267eeaf93966'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chats_user_id_1_fkey', 'chats', type_='foreignkey')
    op.drop_constraint('chats_user_id_2_fkey', 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['user_id_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chats', 'users', ['user_id_2'], ['id'], ondelete='CASCADE')
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key('chats_user_id_2_fkey', 'chats', 'users', ['user_id_2'], ['id'])
    op.create_foreign_key('chats_user_id_1_fkey', 'chats', 'users', ['user_id_1'], ['id'])
    # ### end Alembic commands ###
