"""description migration

Revision ID: cb530a7f81ce
Revises: 267eeaf93966
Create Date: 2024-03-06 14:15:53.117193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'cb530a7f81ce'
down_revision: Union[str, None] = '267eeaf93966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('users', 'discription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('discription', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'description')
    # ### end Alembic commands ###
