# Stage 1: Building Python dependencies
FROM tiangolo/uvicorn-gunicorn:python3.10-slim AS python_builder

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
# RUN mkdir /web-build
# # Stage 2: Building Node.js dependencies and generating static files
# FROM node:18 AS node_builder
# WORKDIR /app


# COPY ./web/* ./
# RUN npm install
# RUN npm run generate

# FROM python_builder
# COPY --from=node_builder /app/.output/public /web-build

# Set the command to run your application
CMD alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0 --port 8000
